# Python review

- recall basic python vocabulary
- practice markdown syntax

## Libraries and packages

**library:** is a collection of code that we can use to perform specific tasks in our prorgams. It can be a single file or multiple files. 

**NumPy:**

- core library for numerical computing in Python
- many of libraries use NumPy arrays as their building blocks
- computations on Numpy objects are optiimzed for speed and memory usage 

Let's import NumPy with its **standard abbreviation** 'np': 


In [2]:
import numpy as np 


## Variables

**variable:** a name we assign to a particular object in Python

Example: 

In [3]:
# Assign a small array to variable a
a = np.array([[1,1,2],[3,5,8]])

In [4]:
# Run call with variable name to show value
a


array([[1, 1, 2],
       [3, 5, 8]])

In [5]:
# Use 'print' function to print the value
print(a)

[[1 1 2]
 [3 5 8]]
